/** All option files that belong to the current behavior have to be included by this file. */

#include "Options/Soccer.h"


#include "Options/GameControl/HandleGameState.h"
#include "Options/GameControl/HandlePenaltyState.h"
#include "Options/GameControl/PlayingState.h"
#include "Options/GameControl/ReadyState.h"
#include "Options/GameControl/RoleAssign.h"

#include "Options/HeadControl/HeadControl.h"
#include "Options/HeadControl/LookForward.h"
#include "Options/HeadControl/LookLeft.h"
#include "Options/HeadControl/LookLeftAndRight.h"
#include "Options/HeadControl/LookLeftAndRightFast.h"
#include "Options/HeadControl/LookLeftAndRightDown.h"
#include "Options/HeadControl/LookLeftOrRightWhileDribble.h"
#include "Options/HeadControl/LookAtBall.h"
#include "Options/HeadControl/LookAtOppKeeper.h"
#include "Options/HeadControl/LookAtTeamBall.h"
#include "Options/HeadControl/LookRight.h"

#include "Options/Output/Annotation.h"

#include "Options/Output/ArmMotionRequest/KeyFrameArms.h"

#include "Options/Output/HeadMotionRequest/SetHeadPanTilt.h"
#include "Options/Output/HeadMotionRequest/SetHeadTarget.h"
#include "Options/Output/HeadMotionRequest/SetHeadTargetOnGround.h"
#include "Options/Output/MotionRequest/DribbleRunswift.h"

#include "Options/Output/MotionRequest/FastKick.h"
#include "Options/Output/MotionRequest/GetUpEngine.h"
#include "Options/Output/MotionRequest/InWalkKick.h"
#include "Options/Output/MotionRequest/PathToTarget.h"
#include "Options/Output/MotionRequest/SpecialAction.h"
#include "Options/Output/MotionRequest/Stand.h"
#include "Options/Output/MotionRequest/WalkAtSpeed.h"
#include "Options/Output/MotionRequest/WalkAtSpeedPercentage.h"
#include "Options/Output/MotionRequest/WalkToTarget.h"
#include "Options/Output/MotionRequest/WalkToTarget_SiQiang.h"
#include "Options/Output/MotionRequest/KickForward.h"
#include "Options/Output/MotionRequest/WalkToTargetWithPath.h"
#include "Options/Output/MotionRequest/WalkToPointRunswift.h"
#include "Options/Output/PlaySound.h"

#include "Options/Skills/AlignMent.h"
#include "Options/Skills/ArmContact.h"
#include "Options/Skills/AvoidObstacle.h"
#include "Options/Skills/AvoidObstacleNearby.h"
#include "Options/Skills/AvoidPath.h"
#include "Options/Skills/AvoidShootPath.h"
#include "Options/Skills/Duel.h"
#include "Options/Skills/DynamicDribble.h"
#include "Options/Skills/Dribble.h"
#include "Options/Skills/Dribble2.h"
#include "Options/Skills/GameFinishied.h"
#include "Options/Skills/GetUp.h"
#include "Options/Skills/GoBehindBall.h"
#include "Options/Skills/GoBehindBall2.h"
#include "Options/Skills/GoToBallAndKick.h"
#include "Options/Skills/GoToBallAndKickSide.h"
#include "Options/Skills/GoToBallAndKickDefender.h"
#include "Options/Skills/GoToBallAndKickKeeper.h"
#include "Options/Skills/GoToBallAndKickStriker.h"
#include "Options/Skills/GoToBallAndKickSupporter.h"
#include "Options/Skills/GoSideAndKickBack.h"
#include "Options/Skills/GoToReadyPose.h"
#include "Options/Skills/KeeperHeadControl.h"
#include "Options/Skills/KeeperLocation.h"
#include "Options/Skills/Kick.h"
#include "Options/Skills/FlashKick.h"
#include "Options/Skills/KickOffBehavior.h"
#include "Options/Skills/SimpleKick.h"
#include "Options/Skills/SearchForBall.h"
#include "Options/Skills/SearchForBallTogether.h"
#include "Options/Skills/StrikerKickOff.h"
#include "Options/Skills/TurnOneRound.h"
#include "Options/Skills/TurnToBall.h"
#include "Options/Skills/WalkToBall.h"
#include "Options/Skills/WalkToPose.h"
#include "Options/Skills/WalkToPose_SiQiang.h"
#include "Options/Skills/WalkToPoseBack.h"
#include "Options/Skills/KickBallToPose.h"
#include "Options/Skills/SwiftKick.h"
#include "Options/Skills/AroundBall.h"
#include "Options/Skills/GoToDribblePoint.h"
#include "Options/Skills/GoToShootPoint.h"
#include "Options/Skills/GoToShootPoint2.h"
#include "Options/Skills/GoToShootPointKeeper.h"
#include "Options/Skills/WalkToPoint.h"
#include "Options/Skills/WalkToPointWithPath.h"
#include "Options/Skills/SupporterKickOff.h"
#include "Options/Skills/SupporterKickOffJudge.h"
#include "Options/Skills/StabberKickOff.h"
#include "Options/Skills/StandUp.h"
#include "Options/Skills/WalkToSupporterDefence.h"
#include "Options/Skills/BizhangDribble.h"
#include "Options/Skills/GoToShootPointWithPath.h"
#include "Options/Skills/GoToBallAndKickWithPath.h"
#include "Options/Skills/SearchForBallFast.h"
#include "Options/Skills/TurnThreePart.h"
#include "Options/Skills/GoToShootPointSupporter.h"

#include "Options/Roles/Keeper.h"
#include "Options/Roles/KeeperOld.h"
#include "Options/Roles/Striker.h"
#include "Options/Roles/StrikerOld.h"
#include "Options/Roles/Supporter.h"
#include "Options/Roles/Supporter2.h"
#include "Options/Roles/SupporterOld.h"
#include "Options/Roles/Defender.h"
#include "Options/Roles/DefenderOld.h"
#include "Options/Roles/Stabber.h"
#include "Options/Roles/StabberOld.h"
#include "Options/Roles/Tester.h"

#include "Options/Tools/ButtonPressedAndReleased.h"
