motion_id = keeperBlockLeft
 
"HP   HT    AL1   AL2   AL3   AL4               AR1   AR2   AR3   AR4               LL0   L1   LL2   LL3   LL4   LL5    LR0   LR1   LR2   LR3   LR4   LR5    Int   Dur 
"HY   HP    LSP   LSR   LEY   LER   LWY   LH    RSP   RSR   REY   RER   RWY   RH    LHYP  LHR  LHP   LKP   LAP   LAR    RHYP  RHR   RHP   RKP   RAP   RAR    Int   Dur
"HY	HP	LSP	LSR	LEY	LER	LWY	LH	RSP	RSR	REY	RER	RWY	RH	LHYP	LHR	LHP	      LKP	LAP	LAR	RHYP	RHR	RHP	RKP	RAP	RAR	Int	Dur
"*    *     *     *     *     *     *     *     *     *     *     *     *     *     *     *    *     *     *     *      *     *     *     *     *     *      1     10000
"-    -     -     -     -     -     -     -     -     -     -     -     -     -     -      -   -     -     -     -      -     -     -     -     -     -      1     1000
label start
"站立:
" 0     0     90    10     0      -0    0     0     90    -10   0     0     0     0     -40    0    -32   50    -25   -0     -40     0     -32    50    -25     0     1     500
"版本1.0最开始的动作:
"*    *       90    30    -0    0     -     -       90    -30   0     -     -     -     -55   5.7  -65.0  99.8  -13.0 -7.0   -55   -18   -66   80    7.8   15     1     300
"版本1.1最开始的动作:
" *     *     90    30    -0      0     -     -     90    -30   0     -     -    -    -40    5.7  -65.0  80   5    -7.0   -40   -18   -65   80    5     15     1     400 
stiffness 100 100   100 100 100 100 100 100   100 100 100 100 100 100   100 100 100 100 100 100   100 100 100 100 100 100   500
" HY    HP    LSP   LSR   LEY    LER   LWY    LH    RSP   RSR   REY  RER  RWY  RH    LHYP   LHR  LHP   LKP   LAP   LAR   RHYP   RHR    RHP   RKP    RAP   RAR    Int   Dur
 *     *      90    30    -0      0     -     -     90    -30   0     -    -    -    -40    18  -65.0   80   -8.8   -7.0   -40   -18   -65   80    -8.8     7     1     300 
 "*    *     *     *     *     *     *     *     *     *     *     *     *     *     *     *    *     *     *     *      *     *     *     *     *     *	     1     3000
  *    *     90    30    -5    -47   -     -     103.6  -26.3  5     0     -     -   -50   -17   22    96.3  -63.9 -4.5   -50   -42   -89.4 85.5   16.4   5.9    1     400

" *    *     *     *     *     *     *     *     *     *     *     *     *     *     *     *    *     *     *     *      *     *     *     *     *     *	     1     3000

  *    *     90    30    -5    -47   -     -     103.6  -26.3  5     0     -     -   -50   -17   22    96.3  -63.9 -4.5   -50   -40.7 -62.3 -2.0  54.6    7.1    1     400

"  *    *     100   25    30    0     -     -     103.4 -25.0 60.5  2.8   -     -    -66.7 -16.7 -28  124.2  -44.3 7.3    -66.7 -40.7 -62.3 -2.0  54.6    7.1    1     100 

  *    *     *     *     *     *     *     *     *     *     *     *     *     *     *     *    *     *     *     *      *     *     *     *     *     *	     1     4000

  
label stay
"起身
"HY   HP    LSP   LSR   LEY   LER   LWY   LH    RSP   RSR   REY   RER   RWY   RH   LHYP  LHR   LHP   LKP   LAP   LAR    RHYP  RHR    RHP   RKP    RAP   RAR    Int   Dur
  *     *    90    30   -5     -47   -     -     103.6 -26.3 5     0     -     -    -50   -17   -0    96.3  -63.9 -4.5   -50   -42   -89.4 85.5   16.4   5.9     1    250
"  *     *    90    30   -5     -47   -     -     103.6 -26.3 5     0     -     -     -50   -17   22    96.3  -63.9 -4.5   -50   -42   -89.4 85.5   16.4   5.9     1    450
  *     *    90    22   -45    -20   -     -     90    -22   0     0     -     -     -30   0    -60   120   -50   0      -30   -0    -60   120    -50    -0       1   250
  0     0    90    6.4  -5.2   -6.5  0     0     90    -8.0  9.8   0     0     0     0     0    -60   120   -62    0      0    -0     -60   120   -62     0     1     400
  0     0    90    10   0      -0    0     0     90    -10   0     0     0     0     0     0    -32   50    -25   -0     0     0     -32    50    -25     0     1     500

"transition keeperBlockLeft keeperBlockLeft stay
 " 0     30   90    11.5  -90  -11.5  -90  0      90  -11.5  90    11.5   90    0     0    -0    -45  71.4    -35.1  -0    0    0     -45  71.4  -35.1   0       1     500
"上面这一行是站着防守
transition allMotions extern start

