motion_id = kickBackSoft
"test

label start

stiffness 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 0

"   HY     HP    LSP    LSR    LEY    LER  _LWY_  _LH_     RSP    RSR    REY    RER  _RWY_   _RH_   LHYP    LHR    LHP    LKP    LAP    LAR   RHYP    RHR    RHP    RKP    RAP    RAR Int  Dur

  -0.5    2.3   90.0   10.1  -90.0   -8.2  -90.0   0.0    90.5   -9.8   89.8    8.4   90.0    0.0    0.0    0.0  -21.3   48.9  -27.6    0.1    0.0    0.0  -21.2   49.0  -27.6    0.0   1 1000
  
* *	* * * * * *     * * * * * *		0  -17.8  -18.6  52.1  -31.6  19.1		0  -19.1  -24.6  64.7  -38.2  20.4		1	400

* *	* * * * * *	* * * * * *		* * -8.6 7.1 -4.6 *					*  *  	  *  	 *  *     *		1	400

* *	* * * * * *	* * * * * *		* * 0 0 0 *					*  *  	  *  	 *  *     *		1	400

* *	* 30 * * * *	* -45 * * * *		* -19 * * * *					*  *  	  -90.0 110.7  -60     *		1	1200

* *	* * * * * *	* * * * * *		* * * * * *					*  *  	  *      60.7	*   *		1	200

* *	* * * * * *	* * * * * *		* * * * * *					*  *  	  *      20.7   50.4  *		1	300

* *	* * * * * *	* * * * * *		* * * * * *					*  *  	  -87    *      *     *		1	50

* *	* * * * * *	* * * * * *		* * * * * *					*  *      *      40.7   *     *		1	200

* *	* * * * * *	* * * * * *		* * * * * *					*  *      *      90.7   *     *		1	600

* *	* 25 * * * *	* -35 * * * *		* * * * * *					*  *      *      40.7   10.4  *		1	200

* *	* 20 * * * *	* -25 * * * *		* * * * * *					*  *      -64.6  *      *     *		1	200

* *	* 10 * * * *	* -8.2 * * * *		* * * * * *					0  -19.1  -24.6  64.7  -38.2  20.4		1	500

* *	* * * * * *	* * * * * *		*  -17.8 -18.6  52.1  -31.6  *					* * * * * * 				1	400

"* *  * * * * * *    * * * * * *    * * * * * *   * * * * * *   1 100000

-0.5    2.3   90.0   10.1  -90.0   -8.2  -90.0   0.0    90.5   -9.8   89.8    8.4   90.0    0.0    0.0    0.0  -21.3   48.9  -27.6    0.1    	0.0    0.0  -21.2   49.0  -27.6    0.0  	 1 700

transition allMotions extern start
