motion_id = sitDown
"sit down after standing

label start
"   HY     HP    LSP    LSR    LEY    LER  _LWY_  _LH_     RSP    RSR    REY    RER  _RWY_   _RH_   LHYP     LHR    LHP    LKP    LAP       LAR   RHYP    RHR    RHP    RKP    RAP    RAR Int  Dur
stiffness * * 40 40 40 40 40 40 40 40 40 40 40 40 * * * * * * * * * * * * 10

 " -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -   1  1000000
   0.0   -0.7   20.8    5      4.6   -2.6  -90.0   0.0    20.8   -5     -4.6    2.6   90.0   0.0       -15.0    0.0  -50.0  114.0  -67.8    0    -15.0    0.0  -50.0  114.0  -67.8    0.0   1 2000

" *    *     *     *     *     *     *     *     *     *     *     *     *     *     *     *    *     *     *     *      *     *     *     *     *     *      1     300 
"0	0	90	10	0	0	0	0	90	-10	0	0	0	0	0	0	-28	50	-25	0	0	0	-28	50	-25	0	1	800

" *    *     *     *     *     *     *     *     *     *     *     *     *     *     *     *    *     *     *     *      *     *     *     *     *     *      1     30000 
stiffness * * 40 40 80 80 40 40 40 40 80 80 40 40 40 40 40  40 40 40 40 40 40 40 40 40 10
    0.0    -0.7   5.8   0      4.6   -2.6  -90.0    0.0   5.8     0     -4.6    2.6   90.0    0.0	-27	-18	-85	123	-70	2.5	-27	18	-85	123	-70	2.5	1	3000
 " 0.0    -0.7   5.8   0      4.6   -2.6  -90.0    0.0   5.8     0     -4.6    2.6   90.0    0.0      -30.0   0.0  -120.0  114.0  -67.8    0.0    -30.0    0.0  -120.0  114.0  -67.8    0.0   1 3000
*    *     *     *     *     *     *     *     *     *     *     *     *     *     *     *    *     *     *     *      *     *     *     *     *     *      1     3000

 "    -      -   51.3    3.5   14.7  -35.8  -90.0   0.0    51.3   -3.5  -14.7   35.8   90.0   0.0     -      -   -50.0      -      -      -      -      -  -50.0      -      -      -   1  500


"*    *     *     *     *     *     *     *     *     *     *     *     *     *     *     *    *     *     *     *      *     *     *     *     *     *      1     3000

"     -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -  -120.0      -      -      -      -      -  -120.0      -      -      -   1  500

label repeat

     -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -   1  100

transition sitDown sitDown repeat

transition allMotions extern start
